services:
  db:
    image: mariadb:11
    expose:
      - "3306"
    ports:
      - "33068:3306"
    environment:
      MARIADB_ROOT_PASSWORD: supersecret
      MARIADB_DATABASE: keycloak
      MARIADB_USER: keycloakuser
      MARIADB_PASSWORD: keycloakpassword
    volumes:
      - db:/var/lib/mysql
  keycloak:
    image: quay.io/keycloak/keycloak:26.2.4
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DEBUG: 'true'
      KC_DB: 'mariadb'
      KC_DB_URL_HOST: 'db'
      KC_DB_URL_DATABASE: 'keycloak'
      KC_DB_USERNAME: 'keycloakuser'
      KC_DB_PASSWORD: 'keycloakpassword'
      DEBUG_PORT: '*:8787'
    ports:
      - "8456:8080"
      - "8457:8787"
    command:
      - 'start-dev'
      - '--http-port'
      - '8080'
      - '--debug'
    volumes:
      - providers:/opt/keycloak/providers/
      - type: bind
        source: ./providers
        target: /opt/keycloak/providers/
  keycloak-config-cli:
    image: adorsys/keycloak-config-cli:latest-26
    environment:
      KEYCLOAK_URL: http://keycloak:8080/
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_AVAILABILITYCHECK_ENABLED: true
      KEYCLOAK_AVAILABILITYCHECK_TIMEOUT: 120s
      IMPORT_FILES_LOCATIONS: '/managed-realms/*'
    volumes:
      - type: bind
        source: ./managed-realms
        target: /managed-realms

volumes:
  db:
    driver: local
